class CountryList {

  Map<String, String> items = {
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AD": "Andorra",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AM": "Armenia",
    "AU": "Australia",
    "AT": "Austria",
    "BO": "Bolivia ",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "CV": "Cabo Verde",
    "KH": "Cambodia",
    "CA": "Canada",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "EG": "Egypt",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FR": "France",
    "GE": "Georgia",
    "DE": "Germany",
    "GR": "Greece",
    "HK": "Hong Kong",
    "IS": "Iceland",
    "ID": "Indonesia",
    "IT": "Italy",
    "JP": "Japan",
    "NZ": "New Zealand",
    "SI": "Slovenia",
    "ZA": "South Africa",
    "ES": "Spain",
    "TR": "Turkey",
    "UA": "Ukraine",
  };

}